# -*- coding: utf-8 -*-
"""data_processing_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUMxmvQGigB0TjhNVh6S614VtIyNuTkB
"""

import pandas as pd

df=pd.read_csv('/content/Advertising_data_set.csv')

print(df.head())

print(df.tail())

print(df.info())

print(df.shape[0])

print(df.shape[1])