# -*- coding: utf-8 -*-
"""dictionary_in_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVoTUxLxRlMgbnsyNXs_iZnUODfby4wg

A Python dictionary is a **mutable, unordered collection of key-value pairs that allows for efficient data retrieval using unique keys**.  Unlike lists, which use numeric indices, dictionaries use immutable keys (such as strings, numbers, or tuples) to map directly to associated values, which can be of any data type.

Keys are unique but values are duplicated
"""

#creation of dictionary
my_dict = {"name" : "Sohan","age" : 21, "Branch" : "ECE"}
print(my_dict)
print(my_dict["name"])
print(my_dict["age"])
print(my_dict["Branch"])

#adding new value to dictionary, and updating dictionary
my_dict["grade"] = "A"
print(my_dict)
my_dict["Branch"] = "B.tech ECE"
print(my_dict)

#deleting data from dictionary
print(my_dict)

#iterating through dictionary
for i,j in my_dict.items():
    print(i,j)

